[Definition]
failregex = ^<HOST> -.*"(GET|POST|HEAD).*?(?:wp-login\.php|xmlrpc\.php|\.env|composer\.json|package\.json|phpunit\.xml|\.git|/\.svn|/\.hg|/docker-compose\.yml|/README|/LICENSE).*" 404
ignoreregex =
